repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: pretty-format-json
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.5
    hooks:
    -   id: clang-format
